# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Make It So
  jobs:
  - job: Do The Thing
    pool:
      vmImage: 'ubuntu-latest'
      PackageDeps: libboost-dev
    steps:
    - script: |
        cmake .
        make
        ./event_test
      displayName: 'Build and Run'
