# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Make_It_So
  jobs:
  - job: Do_The_Thing
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        GCC7:
          PackageDeps: libboost-dev googletest
    steps:
    - script: sudo apt --yes install $(PackageDeps)
      displayName: 'Install Package Dependencies'
    - script: cmake -DCMAKE_PREFIX_PATH=./OpenDDS .
      displayName: 'Configuration'
    - script: make
      displayName: 'Compile'
    - script: ./event_test
      displayName: 'Run Tests'
